export default {
  BLACK: '#000000',
  WHITE: '#FFFFFF',
  CHARCOAL: '#333333',
  LIGHTEST_GREY: '#EFEEF3',
  LIGHT_GREY: '#BBBBBB',
  MEDIUM_GREY: '#CCCCCC',
  DARK_GREY: '#111111',
  BRAND: '#35568D',
  // WARN: '#D63A59',
  CONFIRM: '#3DCF8A',
  ACCENT: '#E89835',
  TRANSPARENT: 'transparent',

  // new color scheme 
  PRIMARY_BRAND_MAIN: '#35568D',
  PRIMARY_BRAND_LIGHT: '#95A7C6',
  PRIMARY_BRAND_GRADIENT: '#2F4D7D',

  SECONDARY_BRAND_MAIN: '#4DDFBC',
  SECONDARY_BRAND_LIGHT: '#BBE8DD',

  PRIMARY_BACKGROUND: '#F5F9FF',
  SECONDARY_BACKGROUND: '#FFFFFF',

  ERROR: '#EC7070',
  WARN: '#ECB370',
  HIGH_CONTRAST: '#1C2A40',

}
